### ISSUE TITLE
The link to the project

### ISSUE THREAD

**Issue by IsmailChangezi** [IsmailChangezi/space-travellers-react#25]
This is the link to the project.
https://github.com/IsmailChangezi/space-travellers-react/projects/1

**Comment by Olamarx** [comment]
Hi @IsmailChangezi, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

While I understand the frustration of waiting for a response from Student Success, kindly note that the permission for you to work on the group project alone as a solo can only come from student success as they are the ones who made the pairing and not us as code reviewers. Kindly be patient and student success will get back to you shortly. You can also send a reminder but not as another ticket, but as a reply from the one you have sent before.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @Ofarouq310 and @IsmailChangezi,

✔️ Tasks are properly assigned

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
